%% vim:ft=erlang:

case os:getenv("TRAVIS_JOB_ID") of
    false -> CONFIG;
    JobId ->
        %% coveralls.io.
        [{plugins, [{coveralls,
                     {git, "https://github.com/markusn/coveralls-erl",
                      {branch, "master"}}}]}
        ,{coveralls_coverdata, "_build/test/cover/eunit.coverdata"}
        ,{coveralls_service_name, "travis-ci"}
        ,{coveralls_service_job_id, JobId}
         |CONFIG
        ]
end.
